config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: %i[show edit update] do
    resources :characters
  end

  get "profile", to: "users#profile"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_one :game
  has_many :characterclasses
  has_many :dnd_classes, through: :characterclasses

  RACES = %w[human elf dwarf halfling gnome half-elf half-orc tiefling aasimar dragonborn goliath]

  validates :name, presence: true
  validates :race, inclusion: { in: RACES }
  validates :bio, presence: true, length: { minimum: 50, maximum: 700 }

  has_many :dnd_class, through: :characterclass
  has_many :dnd_subclass, through: :characterclass
end

app/models/character_campaign.rb
class CharacterCampaign < ApplicationRecord
  belongs_to :character
  belongs_to :campaign
end

app/models/character_class.rb
class Characterclass < ApplicationRecord
  belongs_to :character_id
  belongs_to :dnd_class
  belongs_to :dnd_subclass
end

app/models/characterclass.rb
class Characterclass < ApplicationRecord
  belongs_to :character_id
  belongs_to :dnd_class
  belongs_to :dnd_subclass
end

app/models/dnd_class.rb
class DndClass < ApplicationRecord
  has_one :game
  has_many :characterclasses
  has_many :characters, through: :characterclasses
  has_many :dnd_subclasses, dependent: :destroy

  validates :class_name, presence: true
  validates :description, presence: true
end

app/models/dnd_subclass.rb
class DndSubclass < ApplicationRecord
  belongs_to :dnd_class
  has_many :characterclasses
  has_many :characters, through: :characterclasses

  # if character.game.system == "D&D 5"
  #   case character.dnd_class.class_name
  #   when "Artificier"
  #     DND5SUBCLASSES = ["Alchimiste", "Artilleriste", "Ingénieur de Guerre", "Armurier"]
  #   when "Barbare"
  #     DND5SUBCLASSES = ["Sentinelle Ancestrale", "Berserker", "Sentinelle Totémique"]
  #   when "Barde"
  #     DND5SUBCLASSES = ["Collège du Savoir", "Collège de la Valliance", "Collège de l'Épée", "Collège de l'Eloquence"]
  #   when "Clerc"
  #     DND5SUBCLASSES = ["Domaine de la Connaissance", "Domaine de la Guerre", "Domaine de la Lumière", "Domaine de la Nature", "Domaine de la Tempête", "Domaine de la Vie"]
  #   when "Druide"
  #     DND5SUBCLASSES = ["Cercle de la Lune", "Cercle de la Terre", "Cercle des Spores", "Cercle des Étoiles", "Cercle des Feux de Fôret", "Cercle des Rêves", "Cercle des Bergers"]
  #   when "Ensorceleur"
  #     DND5SUBCLASSES = ["Lignée Draconique", "Magie Sauvage", ]
  #   when "Guerrier"
  #     DND5SUBCLASSES = ["Archétype du Champion", "Archétype du Maître d'Armes", "Archétype du Chevalier Occulte"]
  #   when "Magicien"
  #     DND5SUBCLASSES = ["École de l'Abjuration", "École de l'Enchantement", "École de l'Évocation", "École de l'Illusion", "École de la Divination", "École de la Nécromancie", "École de la Transmutation"]
  #   when "Moine"
  #     DND5SUBCLASSES = ["Voie de l'Élémentaliste", "Voie de l'Ombre", "Voie de la Poigne de Fer"]
  #   when "Paladin"
  #     DND5SUBCLASSES = ["Serment de la Rédemption", "Serment des Anciens", "Serment de la Couronne", "Serment de la Dévotion", "Serment de la Conquête", "Serment de la Gloire", "Serment de la Vengeance"]
  #   when "Rôdeur"
  #     DND5SUBCLASSES = ["Conclave des Animaux", "Conclave des Chasseurs", "Conclave des Ombres"]
  #   when "Roublard"
  #     DND5SUBCLASSES = ["Assassin", "Escroc arcanique", "Voleur"]
  #   when "Occultiste"
  #     DND5SUBCLASSES = ["Archifée", "Le Fiélon", "Le Grand Ancien"]
  #   end
  # end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :characters
  has_many :dnd_class
  has_many :dnd_subclass

  SYSTEMS = ["D&D 5", "Pathfinder"]

  validates :system, inclusion: { in: SYSTEMS }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :characters
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :username, presence: true, uniqueness: true
  validates :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :city, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :city, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    @characters = Character.all
  end

  def show
    @character = Character.find(params[:id])
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.save
    redirect_to character_path(@character)
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params)
    redirect_to character_path(@character)
  end

  def delete
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_path
  end

  private

  def character_params
    params.require(:character).permit(:name, :race, :bio, :game_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  # authenticate for all other pages except home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :city, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/character/_character-card.html.erb
<div class="flexbox">
  <div class="flexitem">
    <img class="avatar-card" src="https://upload.wikimedia.org/wikipedia/en/e/e5/D%26d2.jpg" alt="image of dungeon and dragon">
    <!-- placeholder until we find an image generator or something -->
  </div>
  <div class="flexitem">
    <h3><%= @character.name %></h3>
  </div>
  <div class="flexitem">
    <p><%= @character.dnd_class %> - <%= @character.dnd_subclass %> - <%= @character.role %></p>
    <!-- TODO : split the array of dnd_class & dnd_subclass -->
  </div>
  <div class="flexitem">
    <button class="btn-recruit">Recruit</button>
    <!-- TODO : Javascript to invite the character to a campaign -->
  </div>
</div>

app/views/character/edit.html.erb
<h1>Character#edit</h1>
<p>Find me in app/views/character/edit.html.erb</p>

app/views/character/index.html.erb
<h1>Characters for "game"</h1>

<%= render "character-card" %>
<p>Find me in app/views/character/index.html.erb</p>

app/views/character/new.html.erb
<h1>Create a character</h1>

<%= simple_form_for [@user, @character] do |f| %>
  <%= f.label :game, "First, choose a game" %><br />
  <%= f.select :game, Game::SYSTEMS %> <!-- this is a dropdown -->
  <%= f.input :name,
              required: true,
              input_html: { autocomplete: "Name of your character" } %>
  <%= f.label :dnd_class, "Choose a class" %><br />
  <%= f.select :dnd_class, Dnd_class::DNDCLASSES %> <!-- this is a dropdown -->
  <!-- TODO : Dependending on the game, the dndclasses dropdown has to change -->
  <%= f.label :dnd_subclass, "Choose a subclass" %><br />
  <%= f.select :dnd_subclass, Dnd_subclass::DND5SUBCLASSES %> <!-- this is a dropdown -->
  <!-- TODO : Dependending on the dndclasses, the dndsubclasses dropdown has to change -->
  <%= f.input :role %>
  <!-- TODO : Is there any role ? Not in the model or migration yet -->
  <%= f.label :character, "Race of your character" %><br />
  <%= f.select :character, Character::RACES %> <!-- this is a dropdown -->
  <%= f.input :bio,
              required: true,
              input_html: { autocomplete: "Write a little story to your character"} %>
<% end %>

app/views/character/show.html.erb
<h1>Character#show</h1>
<p>Find me in app/views/character/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TtHomies</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Logo_TTH.svg", alt: "Table Top Homies"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link text-light" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profil", profile_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<h1>Welcome home, <%= @user.username %>!</h1>

<p>Find me in app/views/user/my_profile.html.erb</p>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>